### ISSUE TITLE
Social data fails.

### ISSUE THREAD

**Issue by risto1913** [eiriklv/collectify#2]
interprocess-push-stream:transmitter channel: +0ms errors data: [Error: request for social data failed]
  collectify:main-app error-stream +2ms [Error: request for social data failed]
Error: request for social data failed
    at Request._callback (/xxx/xxx/xxx/xxx/xxx/collectify/node_modules/social-data/lib/req.js:33:18)
    at Request.self.callback (/xxx/xxx/xxx/xxx/xxx/collectify/node_modules/social-data/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/xxx/xxx/xxx/xxx/xxx/collectify/node_modules/social-data/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/xxx/xxx/xxx/xxx/xxx/collectify/node_modules/social-data/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

**Comment by eiriklv** [comment]
Sadly, twitter has decided not to support API calls for getting counts anymore https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

Which was the reason for failing

**Comment by eiriklv** [comment]
Fixed/deprecated now :-)
